trigger:
- '*'

pool:
  name: 'Default' #test

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    command: 'install'
    verbose: false

# ✅ Sass compilation with Bash shell and directory check
- script: |
    if [ -d "Tailspin.SpaceGame.Web/wwwroot/scss" ]; then
      echo " SCSS directory found. Compiling..."
      npx sass Tailspin.SpaceGame.Web/wwwroot/scss:Tailspin.SpaceGame.Web/wwwroot/css
    else
      echo "⚠️ SCSS directory not found. Skipping Sass compilation."
    fi
  displayName: 'Compile Sass assets'
  shell: bash

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: |
    echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
